GET http://localhost:3000/localhost:3000/disneyCharacter

###

GET http://localhost:3000/localhost:3000/disneyCharacter


###

Post http://localhost:3000/disneyCharacter
Content-Type: application/json

{
    "name": "Mickey Mouse",
    "details": "First Character from Disney"
}

###

###